/* ============================================
   TimeWitness — Language Toggle (EN / 中文)
   ============================================ */

document.addEventListener('DOMContentLoaded', () => {
  const toggle = document.getElementById('lang-toggle');
  if (!toggle) return;

  let currentLang = localStorage.getItem('tw-lang') || 'en';
  applyLang(currentLang);

  toggle.addEventListener('click', () => {
    currentLang = currentLang === 'en' ? 'zh' : 'en';
    localStorage.setItem('tw-lang', currentLang);
    applyLang(currentLang);
  });

  function applyLang(lang) {
    toggle.textContent = lang === 'en' ? 'EN / 中文' : '中文 / EN';

    document.querySelectorAll('[data-i18n]').forEach(el => {
      const key = el.getAttribute('data-i18n');
      if (translations[key]) {
        if (el.tagName === 'INPUT' && el.hasAttribute('placeholder')) {
          el.placeholder = translations[key][lang] || translations[key]['en'];
        } else {
          el.innerHTML = translations[key][lang] || translations[key]['en'];
        }
      }
    });

    document.documentElement.lang = lang === 'zh' ? 'zh-CN' : 'en';
  }
});

/* ── Translation Map ── */
const translations = {
  'auto.a_2': { en: 'Skip to main content', zh: '跳至主要内容' },
  'auto.div_3': { en: 'TimeWitness', zh: 'TimeWitness' },
  'auto.div_4': { en: '时间证明', zh: '时间证明' },
  'nav.how': { en: 'How It Works', zh: '使用方式' },
  'nav.features': { en: 'Features', zh: '功能特点' },
  'nav.usecases': { en: 'Use Cases', zh: '使用场景' },
  'nav.permanence': { en: 'Permanence', zh: '持久保存' },
  'nav.pricing': { en: 'Pricing', zh: '价格' },
  'nav.faq': { en: 'FAQ', zh: '常见问题' },
  'auto.button_5': { en: 'EN / 中文', zh: 'EN / 中文' },
  'cta.waitlist': { en: 'Join Waitlist', zh: '加入等待列表' },
  'hero.eyebrow': { en: 'Digital Time Capsule for Life, Love, Family, and Promises', zh: '为生活、爱情、家庭和承诺打造的数字时间胶囊' },
  'hero.h1': { en: 'Let Time Witness What Matters.', zh: '让时间见证重要的一切。' },
  'auto.p_6': { en: '让时间见证重要的一切', zh: '让时间见证重要的一切' },
  'hero.sub': { en: 'TimeWitness helps you write to your future self, preserve family memories, seal relationship promises, and verify long-term commitments — then reopen them years later with timed delivery, identity recovery, and permanence-focused storage.', zh: 'TimeWitness帮助您给未来的自己写信，保存家庭记忆，封存感情承诺，验证长期承诺——然后在数年后通过定时投递、身份找回和永久存储重新打开。' },
  'hero.supporting': { en: 'Write today. Meet yourself, your memories, and your promises in the future.', zh: '今天写下。在未来遇见自己、记忆和承诺。' },
  'cta.how': { en: 'See How It Works', zh: '了解使用方式' },
  'auto.span_7': { en: '10–100 Year Capsules', zh: '10-100年时间胶囊' },
  'auto.span_8': { en: 'WeChat + Email Delivery', zh: '微信 + 邮件准时投递' },
  'auto.span_9': { en: 'Identity Recovery', zh: '身份找回与保护' },
  'auto.span_10': { en: 'Long-Term Preservation', zh: '跨世纪永久保存' },
  'hero.micro': { en: 'No spam. Early access, launch updates, and your first future-letter template.', zh: '无垃圾邮件。早期访问、发布更新和您的第一个未来信件模板。' },
  'auto.span_11': { en: '10Y', zh: '10年' },
  'auto.span_12': { en: '30Y', zh: '30年' },
  'auto.span_13': { en: '100Y', zh: '100年' },
  'auto.div_14': { en: 'Write to Future Me', zh: '写给未来的我' },
  'auto.span_15': { en: 'Opening Date', zh: '开启日期' },
  'auto.span_16': { en: 'January 1, 2045', zh: '2045年1月1日' },
  'auto.span_17': { en: 'Capsule Type', zh: '胶囊类型' },
  'auto.span_18': { en: 'Private Letter', zh: '私人信件' },
  'auto.span_19': { en: 'Delivery', zh: '投递方式' },
  'auto.span_20': { en: 'Email + App + WeChat', zh: '邮件 + App + 微信' },
  'auto.div_21': { en: 'Seal Until the Future', zh: '封存至未来' },
  'auto.p_22': { en: 'From a fragile mailbox to a permanent digital promise', zh: '从脆弱的邮箱到永久的数字承诺' },
  'origin.h2': { en: 'Thirty years ago, people trusted a warehouse of letters. Today, we can build something stronger.', zh: '三十年前，人们信赖一个信件仓库。今天，我们可以构建更强大的东西。' },
  'auto.p_23': { en: 'Decades ago, people wrote letters to themselves or to society and placed them in physical mailboxes to be mailed 10, 20, 30, or even 50 years later. Many never arrived because addresses changed, phone numbers disappeared, and the original system depended on one person and one place.', zh: '几十年前，人们写信给未来的自己或社会，并将它们放在实体邮箱中，期望在10年、20年、30年甚至50年后寄出。许多信件永远没有送达，因为地址改变了，电话号码消失了，而且最初的系统依赖于单个人和单一地点。' },
  'auto.p_24': { en: 'TimeWitness brings that romantic idea into the digital age: a global time-capsule app designed for long-term storage, multi-channel delivery, identity-based account recovery, and decentralized continuity.', zh: 'TimeWitness将这个浪漫的想法带入数字时代：一个全球性的时间胶囊应用，专为长期存储、多渠道投递、基于身份的账户恢复和去中心化的连续性而设计。' },
  'auto.h4_25': { en: 'Then', zh: '过去' },
  'auto.p_26': { en: 'Physical letters, lost addresses, fragile storage', zh: '实体信件、丢失的地址、脆弱的存储' },
  'auto.h4_27': { en: 'Now', zh: '现在' },
  'auto.p_28': { en: 'Digital capsules, identity recovery, redundant backup, future delivery', zh: '数字胶囊、身份找回、冗余备份、未来投递' },
  'auto.a_29': { en: 'See what a modern time capsule can do', zh: '看看现代时间胶囊能做什么' },
  'auto.p_30': { en: 'The platform', zh: '关于平台' },
  'what.h2': { en: 'Not just a letter app. A long-term memory infrastructure.', zh: '不仅仅是信件应用。是一个长期记忆基础设施。' },
  'auto.p_31': { en: 'TimeWitness lets people seal meaningful content today and reopen it when time gives it new meaning. It serves individuals, relationships, families, organizations, and society.', zh: 'TimeWitness让人们今天封存有意义的内容，并在时间赋予其新意义时重新打开。它服务于个人、关系、家庭、组织和社会。' },
  'auto.h3_32': { en: 'Preserve the Self', zh: '保存自我' },
  'auto.p_33': { en: 'Write your dreams, fears, goals, predictions, and reflections. Years later, rediscover the person you used to be.', zh: '写下你的梦想、恐惧、目标、预测和反思。多年以后，重新发现曾经的自己。' },
  'auto.h3_34': { en: 'Preserve Relationships', zh: '保存关系' },
  'auto.p_35': { en: 'Couples, friends, classmates, mentors, and teams can create shared capsules and reopen them together.', zh: '情侣、朋友、同学、导师和团队可以创建共享胶囊并一起重新打开。' },
  'auto.h3_36': { en: 'Preserve Family Memory', zh: '保存家族记忆' },
  'auto.p_37': { en: 'Build a digital family archive with photos, stories, oral history, milestones, family mottos, and messages across generations.', zh: '建立一个包含照片、故事、口述历史、里程碑、家训和跨代留言的数字家庭档案。' },
  'auto.h3_38': { en: 'Preserve Commitments', zh: '保存承诺' },
  'auto.p_39': { en: 'Seal important promises, contracts, signing moments, public statements, and goals for future verification and review.', zh: '封存重要的承诺、合同、签约时刻、公开声明和目标，以供未来验证和回顾。' },
  'auto.p_40': { en: 'The signature experience', zh: '特色体验' },
  'arch.h2': { en: 'Self-archaeology: one day, you will meet who you used to be.', zh: '自我考古：终有一天，你会遇见曾经的自己。' },
  'auto.p_41': { en: 'Most apps help you capture the present. TimeWitness helps you compare the present with the future. A letter written at 18, opened at 30. A dream written before a career begins, reopened after it succeeds or changes. A prediction about society, reopened when history has answered.', zh: '大多数应用帮助您记录现在。TimeWitness帮助您将现在与未来进行比较。18岁写下的一封信，30岁打开。在职业生涯开始前写下的梦想，在成功或改变后重新打开。关于社会的预测，在历史给出答案时重新打开。' },
  'auto.p_42': { en: 'Opening a TimeWitness capsule should feel like excavating a former version of yourself — your dreams, your judgment, your courage, your mistakes, and your growth.', zh: '打开TimeWitness胶囊应该感觉像在发掘曾经的自己——你的梦想、判断力、勇气、错误和成长。' },
  'auto.p_43': { en: '"Years later, it is not just an old message. It is a past version of you."', zh: '“多年以后，那不仅是一条旧留言。那是一个曾经的你。”' },
  'btn.first_letter': { en: 'Write your first future letter', zh: '写下你的第一封未来信' },
  'how.h2': { en: 'How TimeWitness works', zh: 'TimeWitness如何运作' },
  'auto.p_44': { en: 'Step 1', zh: '第一步' },
  'auto.h3_45': { en: 'Create your account', zh: '创建账户' },
  'auto.p_46': { en: 'Sign up with phone, email, WeChat, Apple ID, or Google. Verification-code login can automatically create an account.', zh: '使用手机、邮箱、微信、Apple ID或Google注册。验证码登录可自动创建账户。' },
  'auto.p_47': { en: 'Step 2', zh: '第二步' },
  'auto.h3_48': { en: 'Write or upload', zh: '撰写或上传' },
  'auto.p_49': { en: 'Use the in-app editor with elegant paper and font templates, or upload photos of handwritten letters. Add photos, audio, video, and documents.', zh: '使用内置编辑器及优雅的信纸和字体模板，或上传手写信件照片。添加照片、音频、视频和文档。' },
  'auto.p_50': { en: 'Step 3', zh: '第三步' },
  'auto.h3_51': { en: 'Choose the future', zh: '选择未来' },
  'auto.p_52': { en: 'Set an opening date: 10, 20, 30, 50, or 100 years. Create multiple capsules, each with its own timeline.', zh: '设置开启日期：10年、20年、30年、50年或100年。创建多个胶囊，每个都有自己的时间线。' },
  'auto.p_53': { en: 'Step 4', zh: '第四步' },
  'auto.h3_54': { en: 'Seal and protect', zh: '封存与保护' },
  'auto.p_55': { en: 'Capsules are stored securely. Users may optionally bind identity information for future account recovery.', zh: '胶囊被安全存储。用户可选择绑定身份信息以便未来找回账户。' },
  'auto.p_56': { en: 'Step 5', zh: '第五步' },
  'auto.h3_57': { en: 'Deliver on time', zh: '准时送达' },
  'auto.p_58': { en: 'When the time arrives, TimeWitness sends reminders through WeChat, email, app notifications, and future channels.', zh: '时间到达时，TimeWitness会通过微信、电子邮件、应用通知及未来渠道发送提醒。' },
  'auto.p_59': { en: 'Step 6', zh: '第六步' },
  'auto.h3_60': { en: 'Open, reflect, renew', zh: '开启、反思、更新' },
  'auto.p_61': { en: 'Mark goals as achieved or not, add reflections, and create the next future capsule.', zh: '标记目标是否实现，添加反思，并创建下一个未来胶囊。' },
  'features.h2': { en: 'Everything worth remembering can become a time capsule.', zh: '一切值得记住的都可以成为时间胶囊。' },
  'auto.h3_62': { en: 'Future Letters', zh: '未来信件' },
  'auto.p_63': { en: 'Write to your future self, your child, your partner, your family, your team, or future society. Capture dreams, decisions, predictions, and promises.', zh: '写给未来的自己、孩子、伴侣、家人、团队或未来社会。记录梦想、决定、预测和承诺。' },
  'auto.h3_64': { en: 'Multiple Time Horizons', zh: '多时间跨度' },
  'auto.p_65': { en: 'Set capsules for 10, 20, 30, 50, or 100 years — or create custom milestones for weddings, graduations, and life goals.', zh: '设置10、20、30、50或100年的胶囊——或为婚礼、毕业和人生目标创建自定义里程碑。' },
  'auto.h3_66': { en: 'Beautiful Writing Experience', zh: '优美的写作体验' },
  'auto.p_67': { en: 'Use elegant digital paper, typography templates, and letter styles. Plain paper is free; premium stationery available as upgrade.', zh: '使用优雅的数字信纸、排版模板和信件样式。普通信纸免费；高级信纸作为升级项提供。' },
  'auto.h3_68': { en: 'Handwritten Uploads', zh: '手写上传' },
  'auto.p_69': { en: 'Take a photo of a handwritten letter and preserve the emotional texture of real ink and paper.', zh: '拍下您的手写信件，保留真实墨水和纸张的情感纹理。' },
  'auto.h3_70': { en: 'Multimedia Capsules', zh: '多媒体胶囊' },
  'auto.p_71': { en: 'Upload photos, videos, audio, contract scans, signing photos, wedding footage, family portraits, certificates, and more.', zh: '上传照片、视频、音频、合同扫描件、签约照片、婚礼影像、全家福、证书等。' },
  'auto.h3_72': { en: 'Shared Authorization', zh: '共享授权' },
  'auto.p_73': { en: 'Grant access to selected people. Permissions include view-only, collaborative notes, joint opening, and automatic sharing.', zh: '授予特定人群访问权限。权限包括仅查看、协作笔记、共同开启和自动共享。' },
  'auto.h3_74': { en: 'On-Time Delivery', zh: '准时送达' },
  'auto.p_75': { en: 'China users receive WeChat pushes. Global users receive email reminders and full HTML letter content. Read opened capsules in the app.', zh: '中国用户接收微信推送。全球用户接收邮件提醒和完整的HTML信件内容。在应用内阅读已开启的胶囊。' },
  'auto.h3_76': { en: 'Account Recovery', zh: '账户恢复' },
  'auto.p_77': { en: 'Even if you change phone numbers, emails, or social accounts, optional identity verification can help recover access years later.', zh: '即使您更换了手机号、邮箱或社交账号，可选的身份验证也能帮您在多年后恢复访问。' },
  'auto.h3_78': { en: 'Outcome Evaluation', zh: '结果评估' },
  'auto.p_79': { en: 'After opening, mark goals as achieved, partially achieved, or not achieved, then add reflections and ratings.', zh: '开启后，将目标标记为已实现、部分实现或未实现，然后添加反思和评分。' },
  'auto.h3_80': { en: 'Family Archive', zh: '家族档案' },
  'auto.p_81': { en: 'Store family gatherings, elders\' oral histories, ancestral photos, family trees, anniversaries, and migration stories.', zh: '存储家庭聚会、长辈口述历史、祖辈照片、家谱、纪念日和迁徙故事。' },
  'auto.h3_82': { en: 'Organization Memory', zh: '组织记忆' },
  'auto.p_83': { en: 'Companies and teams preserve signing moments, contracts, team visions, project goals, and financing milestones.', zh: '公司和团队保存签约时刻、合同、团队愿景、项目目标和融资里程碑。' },
  'auto.h3_84': { en: 'Social Predictions', zh: '社会预测' },
  'auto.p_85': { en: 'Write predictions about society, economy, culture, and technology, creating a future archive of ordinary people\'s thoughts.', zh: '写下对社会、经济、文化和技术的预测，创建普通人思想的未来档案。' },
  'usecases.h2': { en: 'Made for the moments that deserve to survive time.', zh: '为值得跨越时间的时刻而生。' },
  'auto.h3_86': { en: 'Write to your future self', zh: '写给未来的自己' },
  'auto.p_87': { en: 'Record childhood dreams, career goals, wealth goals, study plans, life wishes, and stage-by-stage reflections.', zh: '记录童年梦想、职业目标、财富目标、学习计划、人生愿望和阶段性反思。' },
  'auto.h3_88': { en: 'Messages children can open when they grow', zh: '孩子们长大后可以打开的留言' },
  'auto.p_89': { en: 'Parents can leave letters, photos, and blessings at birth, school entry, adulthood, and other milestones.', zh: '父母可以在孩子出生、入学、成年及其他里程碑时留下信件、照片和祝福。' },
  'auto.h3_90': { en: 'Reopen your vows years later', zh: '多年后重温誓言' },
  'auto.p_91': { en: 'Couples can upload vows, photos, and wedding footage, then reopen them after 7, 10, 20, or more years.', zh: '伴侣可以上传誓言、照片和婚礼影像，然后在7年、10年、20年或更长时间后重新打开。' },
  'auto.h3_92': { en: 'Love promises with a future date', zh: '有未来日期的爱情承诺' },
  'auto.p_93': { en: 'Partners preserve anniversary memories, long-distance promises, proposal moments, and shared goals.', zh: '伴侣保存纪念日回忆、异地恋承诺、求婚时刻和共同目标。' },
  'auto.h3_94': { en: 'Promises between friends', zh: '朋友间的承诺' },
  'auto.p_95': { en: 'Friends seal graduation words, startup vows, shared dreams, and brotherhood commitments for future review.', zh: '朋友们封存毕业留言、创业誓言、共同梦想和兄弟承诺，供未来回顾。' },
  'auto.h3_96': { en: 'Ten-year reunion, remembered', zh: '十年重聚，值得铭记' },
  'auto.p_97': { en: 'Classes, clubs, and alumni groups upload photos, messages, and future goals with collective reminders.', zh: '班级、俱乐部和校友会上传照片、留言和未来目标，并设置集体提醒。' },
  'auto.h3_98': { en: 'A family archive that outlives devices', zh: '超越设备的家庭档案' },
  'auto.p_99': { en: 'Move family memory beyond one person\'s phone and create a shared digital heritage across generations.', zh: '将家庭记忆从个人的手机中移出，创建跨代共享的数字遗产。' },
  'auto.h3_100': { en: 'Record growth and inheritance', zh: '记录成长与传承' },
  'auto.p_101': { en: 'Teachers, mentors, and students preserve learning goals, comments, and blessings for future reopening.', zh: '老师、导师和学生保存学习目标、评语和祝福，供未来重新打开。' },
  'auto.h3_102': { en: 'Seal the moment of commitment', zh: '封存承诺时刻' },
  'auto.p_103': { en: 'Teams preserve contracts, signing photos, meeting videos, original goals, and future evaluation checkpoints.', zh: '团队保存合同、签约照片、会议视频、最初目标和未来评估节点。' },
  'auto.h3_104': { en: 'Let ordinary people leave records', zh: '让普通人留下记录' },
  'auto.p_105': { en: 'Document what you believed, feared, expected, and predicted about the world.', zh: '记录你对这个世界的信仰、恐惧、期望和预测。' },
  'rel.h2': { en: 'Relationship archaeology: remember what you promised together.', zh: '关系考古：记住你们共同许下的承诺。' },
  'auto.p_106': { en: 'TimeWitness is not only about the individual. Couples, families, friends, classmates, teams, and partners can preserve shared memories and shared commitments. Years later, they can reopen the same capsule together and ask: What did we promise? What changed? What survived? What should we begin again?', zh: 'TimeWitness不仅关乎个人。情侣、家庭、朋友、同学、团队和伴侣可以保存共同的回忆和共同的承诺。多年以后，他们可以一起重新打开同一个胶囊，并问：我们曾承诺了什么？什么改变了？什么存留了下来？我们应该重新开始什么？' },
  'auto.span_107': { en: 'Two-person shared capsules', zh: '双人共享胶囊' },
  'auto.span_108': { en: 'Multi-person permission control', zh: '多人权限控制' },
  'auto.span_109': { en: 'Joint opening', zh: '共同开启' },
  'auto.span_110': { en: 'Shared reflections', zh: '共享反思' },
  'auto.span_111': { en: 'Renewed promises', zh: '重申承诺' },
  'btn.create_shared': { en: 'Create a shared capsule', zh: '创建共享胶囊' },
  'auto.p_112': { en: 'Designed for decades', zh: '为数十年设计' },
  'perm.h2': { en: 'The promise is not only to store. The promise is to deliver.', zh: '承诺不仅是存储，更是送达。' },
  'auto.p_113': { en: 'Time capsules only matter if they can survive time. TimeWitness is designed around long-term resilience: redundant servers, backup nodes, encrypted export, blockchain timestamping, open-source core modules, and community-governed continuity planning.', zh: '时间胶囊只有在能跨越时间时才有意义。TimeWitness围绕长期弹性进行设计：冗余服务器、备份节点、加密导出、区块链时间戳、开源核心模块和社区治理的连续性规划。' },
  'auto.h3_114': { en: 'Primary + Backup Nodes', zh: '主节点 + 备份节点' },
  'auto.p_115': { en: 'User data is written to a primary node and synchronized to independent backup nodes across different cloud providers and regions.', zh: '用户数据被写入主节点，并同步到不同云提供商和地区的独立备份节点。' },
  'auto.h3_116': { en: '3-2-1 Backup Principle', zh: '3-2-1 备份原则' },
  'auto.p_117': { en: 'Three copies, two types of storage media, and one offline cold backup help reduce the risk of permanent data loss.', zh: '三份副本，两种类型的存储介质，以及一次离线冷备份有助于降低永久性数据丢失的风险。' },
  'auto.h3_118': { en: 'Blockchain Timestamping', zh: '区块链时间戳' },
  'auto.p_119': { en: 'Capsule metadata such as recipient, delivery time, and content hash can be anchored to a public chain for long-term verification.', zh: '胶囊元数据（如收件人、投递时间和内容哈希）可以锚定在公链上，用于长期验证。' },
  'auto.h3_120': { en: 'Open-Source Core', zh: '开源核心' },
  'auto.p_121': { en: 'Core modules such as storage, scheduled delivery, and verification can be open-sourced after platform stabilization.', zh: '平台稳定后，存储、定时投递和验证等核心模块可开源。' },
  'auto.h3_122': { en: 'DAO / Foundation Continuity', zh: 'DAO / 基金会连续性' },
  'auto.p_123': { en: 'A non-profit foundation or DAO structure can help maintain backup nodes and continuity if the original company cannot operate.', zh: '如果原公司无法运营，非营利基金会或DAO结构可帮助维护备份节点和连续性。' },
  'auto.h3_124': { en: 'Annual Integrity Drills', zh: '年度完整性演练' },
  'auto.p_125': { en: 'Old capsules can be sampled annually to verify readability, recoverability, and delivery logic.', zh: '可每年对旧胶囊进行抽样，验证可读性、可恢复性和投递逻辑。' },
  'auto.h3_126': { en: 'User-Owned Export', zh: '用户所有的导出' },
  'auto.p_127': { en: 'Users can export their encrypted letters and archives for personal storage.', zh: '用户可导出其加密信件和档案进行个人存储。' },
  'auto.h3_128': { en: 'Digital Will', zh: '数字遗嘱' },
  'auto.p_129': { en: 'Users may designate heirs or trusted contacts for long-term digital inheritance.', zh: '用户可指定继承人或信任的联系人进行长期的数字遗产继承。' },
  'security.h2': { en: 'Your memories are personal. Your protection should be serious.', zh: '你的记忆是私人的。你的保护应该是严肃的。' },
  'auto.p_130': { en: 'TimeWitness is built for emotional trust and technical trust. The platform protects private letters, family memories, identity recovery information, and shared permissions with careful security design.', zh: 'TimeWitness为情感信任和技术信任而建立。该平台通过谨慎的安全设计保护私人信件、家庭记忆、身份恢复信息和共享权限。' },
  'auto.h3_131': { en: 'Optional identity protection', zh: '可选的身份保护' },
  'auto.p_132': { en: 'Users may voluntarily bind a national ID number or upload an ID photo for future account recovery. Never required for basic use.', zh: '用户可自愿绑定国民身份证号码或上传身份证照片以备未来账户恢复。基础使用绝非必需。' },
  'auto.h3_133': { en: 'Encrypted storage', zh: '加密存储' },
  'auto.p_134': { en: 'Sensitive recovery information is stored with strong encryption and isolated from ordinary user content.', zh: '敏感的恢复信息使用强加密存储，并与普通用户内容隔离。' },
  'auto.h3_135': { en: 'Hash-first decentralized records', zh: '哈希优先的去中心化记录' },
  'auto.p_136': { en: 'Decentralized nodes store hashes or verification metadata only, never plaintext identity information.', zh: '去中心化节点仅存储哈希或验证元数据，从不存储明文身份信息。' },
  'auto.h3_137': { en: 'Permission control', zh: '权限控制' },
  'auto.p_138': { en: 'Users choose who can view, jointly open, annotate, or receive a capsule.', zh: '用户选择谁可以查看、共同打开、注释或接收胶囊。' },
  'auto.h3_139': { en: 'No ID collection on marketing site', zh: '营销网站不收集ID' },
  'auto.p_140': { en: 'The website waitlist never asks for ID documents. Identity binding belongs inside the secure app flow only.', zh: '网站的等候名单从不要求提供ID文件。身份绑定仅属于安全的应用程序流程内。' },
  'auto.h3_141': { en: 'Transparent privacy promise', zh: '透明的隐私承诺' },
  'auto.p_142': { en: 'Clear links to Privacy Policy, Terms, Data Export, and Security Overview.', zh: '清晰链接至隐私政策、条款、数据导出和安全概览。' },
  'btn.security': { en: 'Read the Security Overview', zh: '阅读安全概述' },
  'auto.p_143': { en: 'Simple enough for everyone', zh: '对每个人都足够简单' },
  'pricing.h2': { en: 'Long-term memory should be affordable.', zh: '长期记忆应当触手可及。' },
  'auto.div_144': { en: 'Best value', zh: '最具价值' },
  'auto.h3_145': { en: 'Annual', zh: '按年' },
  'auto.full_1': { en: '¥12<span style="font-size:0.5em;opacity:0.7" data-i18n="auto.span_146">/year</span>', zh: '¥12<span style="font-size:0.5em;opacity:0.7" data-i18n="auto.span_146">/year</span>' },
  'auto.span_146': { en: '/year', zh: '/年' },
  'auto.p_147': { en: 'About US $1.70 / year', zh: '每年约1.70美元' },
  'auto.li_148': { en: 'First month free', zh: '首月免费' },
  'auto.li_149': { en: 'Unlimited letters during subscription', zh: '订阅期间不限信件数量' },
  'auto.li_150': { en: 'Store multiple capsules', zh: '存储多个胶囊' },
  'auto.li_151': { en: 'Set different opening dates', zh: '设置不同的开启日期' },
  'auto.li_152': { en: 'Delivery continues after subscription ends', zh: '订阅结束后继续投递' },
  'auto.li_153': { en: 'App, WeChat, and email delivery', zh: '应用程序、微信和邮件投递' },
  'auto.a_154': { en: 'Start Free Month', zh: '开始免费月' },
  'auto.h3_155': { en: 'Monthly', zh: '按月' },
  'auto.full_2': { en: '¥2<span style="font-size:0.5em;opacity:0.7" data-i18n="auto.span_156">/month</span>', zh: '¥2<span style="font-size:0.5em;opacity:0.7" data-i18n="auto.span_156">/month</span>' },
  'auto.span_156': { en: '/month', zh: '/月' },
  'auto.p_157': { en: 'Flexible short-term option', zh: '灵活的短期选择' },
  'auto.li_158': { en: 'Month-to-month access', zh: '按月使用权限' },
  'auto.li_159': { en: 'Same core writing and storage features', zh: '相同的核心写作和存储功能' },
  'auto.li_160': { en: 'Higher price to encourage annual', zh: '较高的价格以鼓励年付' },
  'auto.li_161': { en: 'Cancel anytime', zh: '随时取消' },
  'auto.a_162': { en: 'Choose Monthly', zh: '选择月付' },
  'auto.h3_163': { en: 'Memory Add-ons', zh: '记忆扩展' },
  'auto.div_164': { en: 'Optional', zh: '可选' },
  'auto.p_165': { en: 'Premium enhancements', zh: '高级增强功能' },
  'auto.li_166': { en: 'Premium digital letter paper: ¥1/page', zh: 'Premium digital letter paper: ¥1/page' },
  'auto.li_167': { en: 'Physical keepsake cards', zh: '实体纪念卡' },
  'auto.li_168': { en: 'Printed letters and elegant envelopes', zh: '印刷的信件和优雅的信封' },
  'auto.li_169': { en: 'On-chain sealing', zh: '链上封存' },
  'auto.li_170': { en: 'Decentralized storage options', zh: '去中心化的存储选项' },
  'auto.li_171': { en: 'Enterprise packages', zh: '企业套餐' },
  'auto.a_172': { en: 'Explore Add-ons', zh: '探索扩展选项' },
  'auto.p_173': { en: 'Payment methods', zh: '支付方式' },
  'auto.span_174': { en: 'WeChat Pay', zh: '微信支付' },
  'auto.span_175': { en: 'Alipay', zh: '支付宝' },
  'auto.span_176': { en: 'Apple Pay', zh: 'Apple Pay' },
  'auto.full_3': { en: '80,000,000¥960,000,000         10%800,000,000¥9,600,000,000         20%1,600,000,000¥19,200,000,000                 <p class="microcopy" style="color:var(--body-gray)" data-i18n="auto.p_185">Scenario projections based on ¥12/year base subscription revenue only. Excludes premium stationery, physical keepsakes, on-chain sealing, enterprise editions, multimedia storage, and other value-added services.</p>', zh: '80,000,000¥960,000,000         10%800,000,000¥9,600,000,000         20%1,600,000,000¥19,200,000,000                 <p class="microcopy" style="color:var(--body-gray)" data-i18n="auto.p_185">Scenario projections based on ¥12/year base subscription revenue only. Excludes premium stationery, physical keepsakes, on-chain sealing, enterprise editions, multimedia storage, and other value-added services.</p>' },
  'auto.p_185': { en: 'Scenario projections based on ¥12/year base subscription revenue only. Excludes premium stationery, physical keepsakes, on-chain sealing, enterprise editions, multimedia storage, and other value-added services.', zh: '场景预测仅基于12元/年的基础订阅收入。不包括高级信纸、实体纪念品、链上封存、企业版、多媒体存储及其他增值服务。' },
  'btn.investor': { en: 'Request Investor Brief', zh: '索取投资者简报' },
  'faq.h2': { en: 'Frequently Asked Questions', zh: '常见问题' },
  'auto.button_186': { en: 'What is TimeWitness?', zh: '什么是TimeWitness？' },
  'auto.div_187': { en: 'TimeWitness is a digital time-capsule app for letters, memories, promises, family archives, relationship capsules, and long-term commitments.', zh: 'TimeWitness是一个数字时间胶囊应用，用于信件、记忆、承诺、家族档案、关系胶囊和长期承诺。' },
  'auto.button_188': { en: 'Can I write more than one letter?', zh: '我可以写不止一封信吗？' },
  'auto.div_189': { en: 'Yes. Users can create multiple letters or capsules, each with its own opening date.', zh: '可以。用户可以创建多封信或胶囊，每个都有自己的开启日期。' },
  'auto.button_190': { en: 'What opening dates are supported?', zh: '支持哪些开启日期？' },
  'auto.div_191': { en: 'Users can choose long-term horizons such as 10, 20, 30, 50, or 100 years, with custom milestones planned or supported depending on product version.', zh: '用户可以选择10、20、30、50或100年等长远期跨度，根据产品版本计划或支持自定义里程碑。' },
  'auto.button_192': { en: 'How will I receive my letter in the future?', zh: '我将来如何收到我的信？' },
  'auto.div_193': { en: 'TimeWitness can notify users through supported channels such as WeChat, email, and the app. Future channels may include WhatsApp, Facebook, SMS, and other social platforms.', zh: 'TimeWitness可以通过微信、电子邮件和应用程序等受支持的渠道通知用户。未来的渠道可能包括WhatsApp、Facebook、SMS和其他社交平台。' },
  'auto.button_194': { en: 'What if I change my phone number or email?', zh: '如果我换了手机号或邮箱怎么办？' },
  'auto.div_195': { en: 'Optional identity-based recovery helps users recover accounts even if old login methods disappear. Users may verify identity and reset contact details.', zh: '可选的基于身份的恢复可帮助用户找回账户，即使旧的登录方法消失。用户可以验证身份并重置联系方式。' },
  'auto.button_196': { en: 'Is identity binding required?', zh: '是否必须绑定身份？' },
  'auto.div_197': { en: 'No. Identity protection is voluntary. It exists to help users recover access many years later.', zh: '不。身份保护是自愿的。它的存在是为了帮助用户在许多年后恢复访问权限。' },
  'auto.button_198': { en: 'What happens if my subscription ends?', zh: '如果我的订阅结束会怎样？' },
  'auto.div_199': { en: 'Existing sealed letters are not deleted. A paused subscription may limit new writing, but delivery of already-stored letters continues.', zh: '现有密封的信件不会被删除。暂停的订阅可能会限制新的书写，但已经存储的信件的投递将继续。' },
  'auto.button_200': { en: 'Can I share a time capsule with someone?', zh: '我可以和别人共享时间胶囊吗？' },
  'auto.div_201': { en: 'Yes. Shared authorization can allow view-only access, joint opening, collaborative notes, or automatic sharing after maturity.', zh: '可以。共享授权可以允许在成熟后仅查看、联合开启、协作笔记或自动共享。' },
  'auto.button_202': { en: 'Can families use TimeWitness?', zh: '家庭可以使用TimeWitness吗？' },
  'auto.div_203': { en: 'Yes. Families can create long-term digital archives with photos, stories, family trees, elders\' messages, anniversaries, and generational records.', zh: '可以。家庭可以利用照片、故事、家谱、长辈的留言、纪念日和世代记录建立长期的数字档案。' },
  'auto.button_204': { en: 'Can companies use TimeWitness?', zh: '公司可以使用TimeWitness吗？' },
  'auto.div_205': { en: 'Yes. Companies and teams can preserve contracts, signing photos, vision statements, project goals, and milestone records.', zh: '可以。公司和团队可以保存合同、签约照片、愿景陈述、项目目标和里程碑记录。' },
  'auto.button_206': { en: 'Does TimeWitness replace legal notarization?', zh: 'TimeWitness会取代法律公证吗？' },
  'auto.div_207': { en: 'No. TimeWitness may support timestamping, evidence preservation, and third-party witnessing, but it does not replace official legal, court, arbitration, audit, or notary systems.', zh: '不会。TimeWitness可能支持时间戳、证据保存和第三方见证，但它不取代官方的法律、法院、仲裁、审计或公证系统。' },
  'auto.button_208': { en: 'Can I export my data?', zh: '我可以导出我的数据吗？' },
  'auto.div_209': { en: 'Yes. The platform supports encrypted user-owned export so users can keep their own archive.', zh: '可以。该平台支持加密的用户所有的导出，以便用户保留他们自己的档案。' },
  'final.h2': { en: 'Write today. Let time answer.', zh: '今天写下。让时间回答。' },
  'final.sub': { en: 'Start with one letter, one promise, one memory, or one dream. Your future self is waiting.', zh: '从一封信、一个承诺、一段记忆或一个梦想开始。未来的自己正在等你。' },
  'btn.create_letter': { en: 'Create Your First Future Letter', zh: '创建你的第一封未来信' },
  'auto.p_210': { en: 'First month free after launch. No ID upload required on the website.', zh: '上线后首月免费。网站上无需上传ID。' },
  'auto.div_211': { en: 'TimeWitness 时间证明', zh: 'TimeWitness 时间证明' },
  'auto.p_212': { en: 'Let Time Witness What Matters.', zh: '让时间见证重要的一切。' },
  'auto.h4_213': { en: 'Product', zh: '产品' },
  'auto.a_214': { en: 'How It Works', zh: '使用方式' },
  'auto.a_215': { en: 'Features', zh: '功能特点' },
  'auto.a_216': { en: 'Use Cases', zh: '使用场景' },
  'auto.a_217': { en: 'Pricing', zh: '价格' },
  'auto.h4_218': { en: 'Trust', zh: '信任' },
  'auto.a_219': { en: 'Security Overview', zh: '安全概述' },
  'auto.a_220': { en: 'Data Export', zh: '数据导出' },
  'auto.a_221': { en: 'Permanence', zh: '持久保存' },
  'auto.a_222': { en: 'Privacy Policy', zh: '隐私政策' },
  'auto.a_223': { en: 'Terms of Service', zh: '服务条款' },
  'auto.h4_224': { en: 'Company', zh: '公司' },
  'auto.a_225': { en: 'About', zh: '关于' },
  'auto.a_226': { en: 'Contact', zh: '联系我们' },
  'auto.h4_227': { en: 'Connect', zh: '连接' },
  'auto.a_228': { en: 'WeChat', zh: '微信' },
  'auto.a_229': { en: 'Email', zh: '电子邮件' },
  'auto.a_230': { en: 'X / Twitter', zh: 'X / 推特' },
  'auto.a_231': { en: 'Instagram', zh: 'Instagram' },
  'auto.p_232': { en: '© TimeWitness. Built for the memories, promises, and futures that matter.', zh: '© TimeWitness。为那些重要的记忆、承诺和未来而生。' },
  'auto.p_233': { en: 'TimeWitness is a digital time-capsule and long-term memory platform. Future legal, identity, blockchain, and credit-related features are subject to local laws and compliance.', zh: 'TimeWitness是一个数字时间胶囊和长期记忆平台。未来的法律、身份、区块链和信用相关功能均需遵守当地法律法规。' },
};
